---
- name: install httpd package
  hosts: web
  become: true
  tasks:
    - name: install package
      package:
        name: httpd
        state: latest

    - name: copy the fiel
      copy:
        src: index.html
        dest: /var/www/html/

    - name: start the service
      service:
        name: httpd
        state: started
