---
- name: install httpd package
  become: true
  hosts: all
  tasks:
  - name: install httpd
    package:
      name: httpd
      state: latest
  - name: start the service
    service:
      name: httpd
      state: started
